import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/root-index.tsx"),
  route("sitemap.xml", "routes/sitemap-xml.ts"),
  route("robots.txt", "routes/robots-txt.ts"),
  route("api/search/suggest", "routes/api-search-suggest.ts"),
  route("api/media-proxy", "routes/media-proxy.ts"),
  route("api/reconcile", "routes/api-reconcile.ts"),
  route("api/csp-report", "routes/api-csp-report.ts"),
  route("api/admin-actions", "routes/admin-actions.ts"),
  route("api/admin/wallet-sync", "routes/api-admin-wallet-sync.ts"),
  route("auth/callback", "routes/auth-callback.ts"),
  route(":locale", "routes/locale-layout.tsx", [
    index("routes/locale-home.tsx"),
    route("dashboard", "routes/dashboard-layout.tsx", [
      index("routes/dashboard-index.tsx"),
      route("logs", "routes/dashboard-logs.tsx"),
      route("operations", "routes/dashboard-operations.tsx"),
      route("support", "routes/dashboard-support.tsx"),
      route("reviews", "routes/dashboard-reviews.tsx"),
      route("customers/:userId", "routes/dashboard-customer-detail.tsx"),
      route("customers", "routes/dashboard-customers.tsx"),
      route("payments", "routes/dashboard-payments.tsx"),
      route("recharges", "routes/dashboard-recharges.tsx"),
      route("orders/:orderId", "routes/dashboard-order-detail.tsx"),
      route("orders", "routes/dashboard-orders.tsx"),
      route("catalog", "routes/dashboard-catalog.tsx"),
      route("catalog/new", "routes/dashboard-catalog-new.tsx"),
      route("catalog/:productId", "routes/dashboard-product.tsx"),
      route("providers", "routes/dashboard-providers.tsx"),
      route("providers/g2bulk/import", "routes/dashboard-g2bulk-import.tsx"),
      route("providers/g2bulk/vouchers", "routes/dashboard-g2bulk-vouchers.tsx"),
      route("providers/maxstore/import", "routes/dashboard-maxstore-import.tsx"),
      route("providers/batstore/import", "routes/dashboard-batstore-import.tsx"),
      route("sync", "routes/dashboard-sync.tsx"),
      route("appearance", "routes/dashboard-appearance.tsx"),
      route("website", "routes/dashboard-website.tsx"),
    ]),
    route("games", "routes/locale-games.tsx"),
    route("search", "routes/locale-search.tsx"),
    route("forgot-password", "routes/locale-forgot-password.tsx"),
    route("reset-password", "routes/locale-reset-password.tsx"),
    route("profile", "routes/locale-profile.tsx"),
    route("notifications", "routes/locale-notifications.tsx"),
    route("support", "routes/locale-support.tsx"),
    route("telegram-connect", "routes/locale-telegram-connect.tsx"),
    route("login", "routes/locale-login.tsx"),
    route("products", "routes/locale-products.tsx"),
    route("orders", "routes/locale-orders.tsx"),
    route("wallet", "routes/locale-wallet.tsx"),
    route("recharge", "routes/locale-recharge.tsx"),
    route("recharge/pay/:invoiceId", "routes/locale-recharge-pay.tsx"),
    route("recharge/:requestId", "routes/locale-recharge-detail.tsx"),
    route("orders/:orderId", "routes/locale-order-detail.tsx"),
    route("orders/:orderId/invoice", "routes/locale-order-invoice.tsx"),
    route("recharge/:requestId/invoice", "routes/locale-recharge-invoice.tsx"),
    route("checkout/:gameSlug/:offerSlug", "routes/locale-checkout.tsx"),
    route(":section", "routes/locale-section.tsx"),
    route(":category/:slug", "routes/locale-product.tsx"),
    route(":category/:slug/:offerSlug", "routes/locale-offer.tsx"),
  ]),
  route("*", "routes/unlocalized.tsx"),
] satisfies RouteConfig;
